from __future__ import annotations
import csv,json
from pathlib import Path

ROOT=Path(r"C:\오블리비언\v2_work")
G=ROOT/"01_glossary"

TERMS=[
# project/user decisions
("Vitharn","비탄","PROJECT_DECISION","User-confirmed Oblivion terminology"),
# latest Skyrim SST / BOOK / Creation Club
("Jyggalag","지갈렉","LATEST_SST_CONTEXT","Sword of Jyggalag -> 지갈렉의 검"),
("Mythic Dawn","미식 던","LATEST_SST_EXACT","Exact/repeated Skyrim usage"),
("Sheogorath","쉐오고라스","LATEST_SST_EXACT","Exact/repeated Skyrim usage"),
("Molag Bal","몰락 발","LATEST_SST_EXACT","Exact Skyrim usage"),
("Tiber Septim","타이버 셉팀","LATEST_SST_BOOK","Repeated BOOK/LSCR usage"),
("Sancre Tor","생크 토르","LATEST_SST_BOOK","BOOK title/context usage"),
("Nine Divines","나인 디바인","LATEST_SST_CONTEXT","Repeated Skyrim usage"),
("Boethia","보에디아","LATEST_SST_CONTEXT_NAMU","Repeated Skyrim context and current community title; one exact SST row has 보에시아"),
("Golden Saint","골든 세인트","LATEST_SST_CC","Repeated Saints & Seducers Creation Club usage"),
("Golden Saints","골든 세인트","LATEST_SST_CC","Repeated Saints & Seducers Creation Club usage"),
("Dark Seducer","다크 세듀서","LATEST_SST_CC","Repeated Saints & Seducers Creation Club usage"),
("Dark Seducers","다크 세듀서","LATEST_SST_CC","Repeated Saints & Seducers Creation Club usage"),
("Shivering Isles","쉬버링 아일즈","LATEST_SST_CC","Repeated Creation Club/Skyrim usage"),
("Mania","매니아","LATEST_SST_CC_CONTEXT","Saints & Seducers region usage"),
("Dementia","디멘시아","LATEST_SST_CC_CONTEXT","Saints & Seducers region usage"),
("Passwall","패스월","LATEST_SST_CONTEXT","Skyrim Sheogorath dialogue"),
("Haskill","하스킬","LATEST_SST_CONTEXT","Skyrim Sheogorath dialogue"),
("Umaril","우마릴","LATEST_SST_BOOK","Song of Pelinal BOOK usage"),
("Pelinal","펠리날","LATEST_SST_BOOK","Song of Pelinal titles/body"),
("Pelinal Whitestrake","펠리날 화이트스트레이크","LATEST_SST_BOOK","BOOK context; SST Pelinal spelling preferred over community 펠리널"),
("Cyrodiil","시로딜","LATEST_SST_BOOK","Repeated BOOK usage"),
("Ayleid","에일리드","LATEST_SST_BOOK","Repeated BOOK usage"),
("Ayleids","에일리드","LATEST_SST_BOOK","Repeated BOOK usage"),
("Daedra","데이드라","LATEST_SST_BOOK","Repeated BOOK/UI usage"),
("Daedric Prince","데이드릭 프린스","LATEST_SST_CONTEXT","Repeated Skyrim usage"),
("Mehrunes Dagon","메이룬스 데이건","LATEST_SST_CONTEXT","Oblivion Crisis Skyrim usage"),
("Kvatch","크바치","LATEST_SST_CONTEXT","Repeated Skyrim usage"),
("Skingrad","스킨그라드","LATEST_SST_CONTEXT","Skyrim usage"),
("Imperial City","임페리얼 시티","LATEST_SST_CONTEXT","Repeated Skyrim usage"),
("Cheydinhal","체이딘할","LATEST_SST_CONTEXT","Skyrim letter/context usage"),
("Bruma","브루마","LATEST_SST_CONTEXT","Skyrim/Creation Club usage"),
("Bravil","브라빌","LATEST_SST_BOOK","BOOK/guide usage"),
("Chorrol","코롤","LATEST_SST_BOOK","BOOK usage"),
("Leyawiin","레이야윈","LATEST_SST_BOOK","BOOK usage"),
# Oblivion-specific community-established forms, absent/insufficient in Skyrim
("Anvil","앤빌","PROJECT_CONTEXT_OVERRIDE","Cyrodiil city; do not use SST generic 모루"),
("New Sheoth","뉴 쉐오스","NAMUWIKI_COMMUNITY","Current Korean TES community usage"),
("Bliss","블리스","NAMUWIKI_COMMUNITY","Shivering Isles regional list"),
("Crucible","크루시블","NAMUWIKI_COMMUNITY","Shivering Isles regional list"),
("Brellach","브릴라크","NAMUWIKI_COMMUNITY","Shivering Isles regional list"),
("Cylarne","사이란","NAMUWIKI_COMMUNITY","Shivering Isles main quest/community usage"),
("Highcross","하이크로스","NAMUWIKI_COMMUNITY","Shivering Isles regional list"),
("Pinnacle Rock","피나클 락","NAMUWIKI_COMMUNITY","Shivering Isles regional list"),
("Xedilian","제딜리안","NAMUWIKI_COMMUNITY","Shivering Isles regional/main quest usage"),
("The Fringe","프린지","NAMUWIKI_COMMUNITY","Shivering Isles regional list"),
("Fringe","프린지","NAMUWIKI_COMMUNITY","Shivering Isles regional/main quest usage"),
("Split","스플릿","NAMUWIKI_COMMUNITY","Shivering Isles regional list"),
("Hill of Suicides","자살자의 언덕","NAMUWIKI_COMMUNITY","Shivering Isles regional list"),
("Gates of Madness","광기의 관문","NAMUWIKI_COMMUNITY","Shivering Isles regional/main quest usage"),
("Gatekeeper","게이트키퍼","NAMUWIKI_COMMUNITY","Dedicated current community page"),
("Knight of Order","질서의 기사","NAMUWIKI_COMMUNITY","Current Greymarch/main quest usage"),
("Knights of Order","질서의 기사","NAMUWIKI_COMMUNITY","Current Greymarch/main quest usage"),
("Priest of Order","질서의 사제","NAMUWIKI_COMMUNITY","Current Greymarch/main quest usage"),
("Priests of Order","질서의 사제","NAMUWIKI_COMMUNITY","Current Greymarch/main quest usage"),
("Greymarch","회색 행군","NAMUWIKI_CURRENT","Current page title; 그레이마치 redirects here"),
("Thadon","테이돈","NAMUWIKI_COMMUNITY","Current New Sheoth page usage"),
("Syl","실","NAMUWIKI_COMMUNITY","Current dedicated page"),
("Relmyna Verenim","렐미나 베레님","NAMUWIKI_COMMUNITY","Current dedicated page"),
("Aureal","오리얼","NAMUWIKI_COMMUNITY","Golden Saint self-name"),
("Mazken","마즈켄","NAMUWIKI_COMMUNITY","Dark Seducer self-name"),
("Grummite","그루밋","NAMUWIKI_COMMUNITY","Established Korean community title; page notes pronunciation 그러마이트"),
("Baliwog","발리오그","NAMUWIKI_COMMUNITY","Grummite lifecycle page usage"),
("Gnarl","그나르","REMASTER_V1_CONSENSUS","SST Gnarl Bark rendering is inconsistent; remaster/v1 creature usage supports 그나르"),
("Elytra","엘리트라","V1_BOOK_REFERENCE","Stable creature/ingredient rendering in prior BOOK translation"),
("Scalon","스캐론","V1_BOOK_REFERENCE","Stable creature/ingredient rendering in prior BOOK translation"),
("Everscamp","무한 스캠프","NAMUWIKI_COMMUNITY","Current Oblivion follower/community usage"),
# series-wide Oblivion entities and institutions
("Clannfear","클랜피어","NAMUWIKI_COMMUNITY","Current dedicated creature page"),
("Daedroth","데이드로쓰","NAMUWIKI_COMMUNITY","Current Korean TES creature usage"),
("Xivilai","지빌라이","NAMUWIKI_COMMUNITY","Current dedicated Oblivion creature page"),
("Mannimarco","매니마코","NAMUWIKI_COMMUNITY","Current dedicated character page"),
("Fighters Guild","파이터 길드","NAMUWIKI_COMMUNITY","Current Oblivion faction/quest-line usage"),
("Mages Guild","메이지 길드","NAMUWIKI_COMMUNITY","Current Oblivion faction/quest-line usage"),
("Arcane University","아케인 대학","NAMUWIKI_COMMUNITY","Current dedicated location page"),
("Knights of the Nine","나인의 기사단","NAMUWIKI_COMMUNITY","Current dedicated faction page"),
("Priory of the Nine","나인의 수도회","NAMUWIKI_COMMUNITY","Current Knights of the Nine faction page"),
("Weynon Priory","웨이넌 수도원","NAMUWIKI_COMMUNITY","Current dedicated location page"),
("Imperial Legion","제국군","SOL_CONTEXT_CONFIRMED","Prior conflict review; faction sense"),
("Scamp","스캠프","SERIES_STANDARD","Stable Korean TES creature term"),
("Dremora","드레모라","SERIES_STANDARD","Stable Korean TES creature term"),
("Atronach","아트로나크","SERIES_STANDARD","Stable Korean TES creature term"),
("King of Worms","벌레의 왕","NAMUWIKI_COMMUNITY","Mannimarco epithet"),
("Worm Cult","벌레 교단","NAMUWIKI_COMMUNITY","Established community name"),
# Main quest / guild core names
("Jauffre","죠프리","LATEST_SST_BOOK","The Oblivion Crisis BOOK renders Jauffre as 죠프리"),
("Baurus","보러스","LATEST_SST_BOOK_NAMU","Oblivion Crisis BOOK context + current community page"),
("Mankar Camoran","맨카 캐모런","LATEST_SST_BOOK","Commentaries BOOK author line repeatedly uses 맨카 캐모런"),
("Martin Septim","마틴 셉팀","LATEST_SST_BOOK_NAMU","Oblivion Crisis BOOK + current community usage"),
("Uriel Septim","유리엘 셉팀","LATEST_SST_BOOK","Repeated Skyrim BOOK usage"),
("Uriel Septim VII","유리엘 셉팀 7세","LATEST_SST_CONTEXT","Direct Skyrim/Dawnguard usage"),
("Amulet of Kings","왕의 아뮬렛","LATEST_SST_EXACT","Exact Skyrim BOOK title/term"),
("Blades","블레이드","LATEST_SST_EXACT","Faction usage; exact Skyrim/CC entry"),
("Hero of Kvatch","크바치의 영웅","LATEST_SST_BOOK_NAMU","Oblivion Crisis BOOK + current community title"),
("Gray Fox","그레이 폭스","LATEST_SST_CC","Repeated Gray Cowl Creation usage"),
("Lucien Lachance","루시엔 러찬스","LATEST_SST_CONTEXT","Direct Skyrim dialogue"),
("Dark Brotherhood","다크 브라더후드","LATEST_SST_CONTEXT","Repeated Skyrim faction usage"),
("Thieves Guild","도둑 길드","LATEST_SST_CONTEXT","Repeated Skyrim/Dragonborn faction usage"),
("Blade of Woe","비통의 단검","LATEST_SST_EXACT","Exact Skyrim/Creation entry"),
("Mehrunes Razor","메이룬스의 면도칼","NAMUWIKI_COMMUNITY","Current Korean TES artifact title; Skyrim metadata is untranslated"),
("Skeleton Key","해골 열쇠","LATEST_SST_EXACT","Exact Skyrim item and repeated quest usage"),
("Gray Cowl of Nocturnal","녹터널의 회색 가면","LATEST_SST_CC","Exact Gray Cowl Creation entry"),
("Nocturnal","녹터널","LATEST_SST_EXACT","Exact Skyrim NPC and repeated dialogue usage"),
("Night Mother","나이트 마더","LATEST_SST_CONTEXT","Repeated Skyrim Dark Brotherhood usage"),
("Oblivion Gate","오블리비언 게이트","LATEST_SST_EXACT","Exact/BOOK usage"),
("Oblivion Crisis","오블리비언 대위기","LATEST_SST_BOOK","The Oblivion Crisis BOOK title"),
# Race names used in prose/dialogue (RACE/FULL itself still remains English in the plugin)
("Argonian","아르고니안","LATEST_SST_EXACT","Repeated exact Skyrim/CC race usage"),
("Khajiit","카짓","LATEST_SST_EXACT","Repeated exact Skyrim/CC race usage"),
("Altmer","알트머","LATEST_SST_CONTEXT","Repeated Skyrim dialogue/loading usage"),
("Bosmer","보스머","LATEST_SST_CONTEXT","Repeated Skyrim dialogue/loading usage"),
("Dunmer","던머","LATEST_SST_CONTEXT","Repeated Skyrim dialogue/loading usage"),
("Orc","오크","LATEST_SST_EXACT","Repeated exact Skyrim/CC race usage"),
("Orsimer","오시머","LATEST_SST_CONTEXT","Skyrim dialogue usage"),
("Breton","브레튼","LATEST_SST_EXACT","Repeated exact Skyrim race usage"),
("Nord","노드","LATEST_SST_EXACT","Repeated exact Skyrim race usage"),
("Redguard","레드가드","LATEST_SST_EXACT","Repeated exact Skyrim race usage"),
("High Elf","하이 엘프","LATEST_SST_EXACT","Repeated exact Skyrim race usage"),
("Wood Elf","우드 엘프","LATEST_SST_EXACT","Repeated exact Skyrim race usage"),
("Dark Elf","다크 엘프","LATEST_SST_EXACT","Repeated exact Skyrim race usage"),
# Daedric Princes not already defined above
("Azura","아주라","LATEST_SST_EXACT","Exact Skyrim usage"),
("Boethiah","보에디아","LATEST_SST_CONTEXT_NAMU","Repeated Skyrim context + current community title"),
("Clavicus Vile","클라비쿠스 바일","LATEST_SST_EXACT","Exact Skyrim usage"),
("Hermaeus Mora","헤르메우스 모라","LATEST_SST_EXACT","Repeated exact Skyrim usage"),
("Hircine","허씬","LATEST_SST_EXACT","Exact Skyrim usage"),
("Malacath","말라카스","LATEST_SST_EXACT","Exact Skyrim usage"),
("Mephala","메팔라","LATEST_SST_EXACT","Exact Skyrim usage"),
("Meridia","메리디아","LATEST_SST_EXACT","Exact Skyrim usage"),
("Namira","나미라","LATEST_SST_CONTEXT","Repeated Skyrim item/quest usage"),
("Peryite","페리아이트","LATEST_SST_CONTEXT_NAMU","Repeated Skyrim context + current community title"),
("Sanguine","생귀","LATEST_SST_EXACT","Skyrim exact/context usage; community often uses 생귄"),
("Vaermina","베르미나","LATEST_SST_EXACT","Exact Skyrim usage"),
# The Divines
("Akatosh","아카토쉬","LATEST_SST_EXACT","Exact Skyrim usage"),
("Arkay","아케이","LATEST_SST_EXACT","Exact Skyrim usage"),
("Dibella","디벨라","LATEST_SST_EXACT","Exact Skyrim usage"),
("Julianos","줄리아노스","LATEST_SST_EXACT","Exact Skyrim usage"),
("Kynareth","키나레스","LATEST_SST_EXACT","Exact Skyrim usage"),
("Mara","마라","LATEST_SST_EXACT","Exact Skyrim usage"),
("Stendarr","스텐다르","LATEST_SST_EXACT","Exact Skyrim usage"),
("Zenithar","제니타르","LATEST_SST_EXACT","Exact Skyrim usage"),
("Talos","탈로스","LATEST_SST_EXACT","Exact Skyrim usage"),
# Major provinces/planes
("Tamriel","탐리엘","LATEST_SST_EXACT","Exact Skyrim usage"),
("Morrowind","모로윈드","LATEST_SST_CONTEXT","Repeated Skyrim/Dragonborn usage"),
("Skyrim","스카이림","LATEST_SST_EXACT","Repeated exact Skyrim usage"),
("Hammerfell","해머펠","NAMUWIKI_CURRENT_SST_CONFLICT","Current community title; SST context varies between 해머폴/해머펠"),
("High Rock","하이 락","LATEST_SST_CONTEXT","Repeated Skyrim usage"),
("Valenwood","발렌우드","LATEST_SST_CONTEXT","Repeated Skyrim usage"),
("Summerset Isle","서머셋 아일즈","LATEST_SST_CONTEXT_NAMU","Skyrim context and current community regional name"),
("Summerset Isles","서머셋 아일즈","LATEST_SST_CONTEXT_NAMU","Skyrim context and current community title"),
("Black Marsh","블랙 마쉬","LATEST_SST_CONTEXT_NAMU","Skyrim context and current community title"),
("Elsweyr","엘스웨어","LATEST_SST_CONTEXT","Repeated Skyrim usage"),
("Oblivion","오블리비언","LATEST_SST_CONTEXT","Series/plane name in Skyrim usage"),
("Mundus","문두스","LATEST_SST_CONTEXT","Skyrim lore dialogue usage"),
# Major artifacts and recurring Oblivion names
("Staff of Sheogorath","쉐오고라스의 지팡이","LATEST_SST_EXACT","Exact Saints & Seducers/Skyrim usage"),
("Wabbajack","와바잭","LATEST_SST_EXACT","Repeated exact Skyrim usage"),
("Sanguine Rose","생귀의 장미","LATEST_SST_EXACT","Repeated exact Skyrim usage"),
("Mace of Molag Bal","몰락 발의 철퇴","LATEST_SST_EXACT","Repeated exact Skyrim usage"),
("Azura's Star","아주라의 별","LATEST_SST_EXACT","Exact Skyrim usage"),
("Goldbrand","골드브랜드","LATEST_SST_EXACT","Exact Creation/SST usage"),
("Ebony Blade","에보니 블레이드","LATEST_SST_EXACT","Repeated exact Skyrim usage"),
("Oghma Infinium","오그마 인피니움","LATEST_SST_EXACT","Repeated exact Skyrim usage"),
("Ring of Khajiit","카짓의 반지","LATEST_SST_EXACT","Repeated exact SST usage"),
("Ring of Namira","나미라의 반지","LATEST_SST_EXACT","Repeated exact Skyrim usage"),
("Volendrung","볼렌드렁","LATEST_SST_EXACT","Repeated exact Skyrim usage"),
("Spellbreaker","스펠브레이커","LATEST_SST_MAJORITY","SST exact variants favor 스펠브레이커 4:1 over 마법 차단"),
("Mathieu Bellamont","매튜 벨라몬트","LATEST_SST_CONTEXT_NAMU","Skyrim dialogue and current Dark Brotherhood community page"),
("Hannibal Traven","한니발 트레이븐","LATEST_SST_BOOK","Skyrim BOOK The Black Arts On Trial; current community title uses 트래븐"),
("Hieronymus Lex","히에로니무스 렉스","NAMUWIKI_CURRENT","Current dedicated Oblivion community page"),
("Vicente Valtieri","비센테 발티에리","NAMUWIKI_CURRENT","Current dedicated Oblivion community page"),
("Ocheeva","오치바","NAMUWIKI_CURRENT","Current dedicated Oblivion community page"),
("Arquen","아퀜","NAMUWIKI_CURRENT","Current Dark Brotherhood member list"),
("Modryn Oreyn","모드윈 오레인","NAMUWIKI_CURRENT","Current dedicated Oblivion community page"),
("Vilena Donton","빌레나 던튼","NAMUWIKI_CURRENT","Current dedicated Oblivion community page"),
("Ocato","오카토","NAMUWIKI_CURRENT","Current dedicated TES community page"),
("Knights of the Thorn","가시의 기사단","NAMUWIKI_COMMUNITY","Current Oblivion housing/faction usage"),
("Blackwood Company","블랙우드 컴퍼니","NAMUWIKI_CURRENT","Current dedicated Oblivion faction page"),
("Order of the Virtuous Blood","고귀한 피의 결사","NAMUWIKI_CURRENT","Current dedicated Oblivion faction page"),
("Imperial Watch","제국군 경비병","NAMUWIKI_CURRENT","Current Imperial Legion article explicitly maps Imperial Watch"),
("Armand Christophe","아르망 크리스토프","NAMUWIKI_CURRENT","Current Oblivion Thieves Guild member list"),
("Methredhel","메스레델","NAMUWIKI_CURRENT","Current Oblivion Thieves Guild member list"),
("Raminus Polus","라미누스 폴루스","NAMUWIKI_CURRENT","Current Mages Guild quest-line article"),
("Tar-Meena","타르-미나","NAMUWIKI_CURRENT","Current dedicated Oblivion character page"),
("Raven Camoran","레이븐 캐모런","NAMUWIKI_CURRENT","Current Oblivion main-quest article"),
("Ruma Camoran","루마 캐모런","PROJECT_FAMILY_STANDARD","Normalize Camoran family surname to 캐모런; current pages vary 캐모란/캐모런"),
("Nord Winds","노드의 바람","OBLIVION_PROJECT_QA","Oblivion-specific Bruma shop name; prior reviewed translation is consistent"),
]

CONFLICTS=[
("Jyggalag","지갈렉","지갈랙","SST vs NamuWiki","Use latest SST per project priority"),
("Pelinal","펠리날","펠리널","SST BOOK vs NamuWiki","Use latest SST BOOK per project priority"),
("Cheydinhal","체이딘할","셰이딘홀","SST vs older/community Oblivion usage","Use latest SST per project priority"),
("Greymarch","회색 행군","그레이마치","Current Namu title vs older transliteration","Use current community title unless project later overrides"),
("Grummite","그루밋","그러마이트|그루마이트","Namu established vs pronunciation/remaster/v1","Use current community title"),
("Gnarl","그나르","그날스","Remaster/v1 vs one SST ingredient rendering","Use creature-context consensus"),
("Everscamp","무한 스캠프","에버스캠프","Current community semantic name vs older transliteration","Use current community title"),
("Boethiah","보에디아","보에시아","Repeated SST context/community vs one exact SST row","Use repeated context + current community title"),
("Sanguine","생귀","생귄","Latest SST vs current community title","Use latest SST per project priority"),
("Hammerfell","해머펠","해머폴","Current community title vs inconsistent Skyrim SST contexts","Use current community title for consistency"),
("Spellbreaker","스펠브레이커","마법 차단","SST exact variants 4:1","Use majority exact SST form"),
("Hannibal Traven","한니발 트레이븐","한니발 트래븐","Latest Skyrim BOOK vs current community title","Use latest SST BOOK per project priority"),
("Arquen","아퀜","아르퀸","Current Dark Brotherhood page vs Night Mother page","Use current faction member-list spelling; keep conflict documented"),
("Modryn Oreyn","모드윈 오레인","모던 오리언","Current community title vs old v1","Use current community title"),
("Vilena Donton","빌레나 던튼","발레나 던튼","Current community title vs older community spelling","Use current 2026 community title"),
("Ruma Camoran","루마 캐모런","루마 캐모란","Camoran family normalization vs older/current standalone page title","Use family-wide 캐모런 to match Mankar/Raven and latest main-quest usage"),
]

def main():
    seen=set(); rows=[]
    for en,ko,basis,note in TERMS:
        key=en.casefold()
        if key in seen: raise RuntimeError("duplicate "+en)
        seen.add(key)
        rows.append({"source_english":en,"korean":ko,"source_basis":basis,
                     "status":"CONFIRMED","notes":note})
    out=G/"OBLIVION_CORE_TERMINOLOGY_V2.csv"
    with out.open("w",encoding="utf-8-sig",newline="") as f:
        w=csv.DictWriter(f,fieldnames=list(rows[0])); w.writeheader(); w.writerows(rows)
    crows=[{"source_english":a,"selected":b,"alternatives":c,"conflict_basis":d,"resolution":e}
           for a,b,c,d,e in CONFLICTS]
    with (G/"OBLIVION_TERMINOLOGY_CONFLICTS_V2.csv").open("w",encoding="utf-8-sig",newline="") as f:
        w=csv.DictWriter(f,fieldnames=list(crows[0])); w.writeheader(); w.writerows(crows)
    report={"confirmed_core_terms":len(rows),"documented_conflicts":len(crows),
            "basis_counts":{}}
    for r in rows:
        report["basis_counts"][r["source_basis"]]=report["basis_counts"].get(r["source_basis"],0)+1
    (G/"OBLIVION_CORE_TERMINOLOGY_V2_REPORT.json").write_text(
        json.dumps(report,ensure_ascii=False,indent=2),encoding="utf-8")
    print(json.dumps(report,ensure_ascii=True,indent=2))
if __name__=="__main__": main()